---
abstract: 'Postmodern Perl Module Packaging'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Package
name: Module-Package
no_index:
  directory:
    - inc
    - t
requires:
  File::Find: 0
  IO::All: 0.41
  Module::Install::AuthorRequires: 0.02
  Module::Install::ManifestSkip: 0.15
  Moo: 0.009007
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
